version: "3.8"
services:
  db:
    image: postgres:16.4
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app

volumes:
  postgres_data:
